spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.57:3306/bookstore
mybatis:
  mapper-locations: classpath:/mappers/*.xml